// Generated by CoffeeScript 1.3.3
(function() {
  var Graph, http;

  http = require('fibered-http');

  module.exports = Graph = (function() {

    function Graph(token, options) {
      this.token = token;
      if (options == null) {
        options = {};
      }
      if (this.token == null) {
        throw new Error("Facebook token required");
      }
      this.http = options.http || http;
    }

    Graph.prototype.get = function(path, options) {
      var json, query, res;
      if (options == null) {
        options = {};
      }
      query = options.query || {};
      query.access_token = this.token;
      res = this.http.request({
        protocol: 'https',
        hostname: 'graph.facebook.com',
        path: path,
        query: query,
        timeout: options.timeout
      });
      json = null;
      try {
        json = JSON.parse(res.body);
      } catch (e) {
        throw new Error("Unable to parse result of facebook graph call - " + (e.toString()));
      }
      if (json.error) {
        throw new Error("Facebook Graph Error: " + json.error.message);
      }
      return json;
    };

    return Graph;

  })();

}).call(this);
